// AUTO-GENERATED by scripts/generate-element-attrs.mjs
// Source: @webref/idl html.idl — do not edit by hand
// Re-run: node scripts/generate-element-attrs.mjs

export interface AttrInfo {
  name: string
  description: string
  /** Valid tokens for space-separated token-list attributes (rendered as chip picker) */
  tokens?: string[]
  /** Fixed enumerated values (rendered as select) */
  options?: string[]
}

export const iframeAttributes: AttrInfo[] = [
  {
    "name": "srcdoc",
    "description": "Inline HTML to embed, overriding src"
  },
  {
    "name": "name",
    "description": "Targetable name for the browsing context (used with window.open or form targets)"
  },
  {
    "name": "sandbox",
    "description": "Space-separated tokens restricting iframe capabilities (e.g. allow-scripts allow-same-origin allow-forms)",
    "tokens": [
      "allow-downloads",
      "allow-forms",
      "allow-modals",
      "allow-orientation-lock",
      "allow-pointer-lock",
      "allow-popups",
      "allow-popups-to-escape-sandbox",
      "allow-presentation",
      "allow-same-origin",
      "allow-scripts",
      "allow-storage-access-by-user-activation",
      "allow-top-navigation",
      "allow-top-navigation-by-user-activation",
      "allow-top-navigation-to-custom-protocols"
    ]
  },
  {
    "name": "allow",
    "description": "Permissions Policy for the iframe (e.g. camera; microphone; fullscreen)"
  },
  {
    "name": "allowfullscreen",
    "description": "Allows the iframe to enter fullscreen mode via requestFullscreen()"
  },
  {
    "name": "referrerpolicy",
    "description": "Controls how much referrer info is sent: no-referrer, origin, strict-origin, same-origin, unsafe-url",
    "options": [
      "no-referrer",
      "no-referrer-when-downgrade",
      "origin",
      "origin-when-cross-origin",
      "same-origin",
      "strict-origin",
      "strict-origin-when-cross-origin",
      "unsafe-url"
    ]
  },
  {
    "name": "loading",
    "description": "Lazy-load: eager (default) loads immediately, lazy defers until near the viewport",
    "options": [
      "eager",
      "lazy"
    ]
  }
]

export const scriptAttributes: AttrInfo[] = [
  {
    "name": "type",
    "description": "MIME type, or \"module\" (ES module), \"importmap\", or \"speculationrules\"",
    "options": [
      "",
      "module",
      "importmap",
      "speculationrules"
    ]
  },
  {
    "name": "nomodule",
    "description": "Prevents execution in browsers that support ES modules — use for legacy fallback scripts"
  },
  {
    "name": "async",
    "description": "Fetch and execute the script asynchronously, without blocking parsing (classic scripts only)"
  },
  {
    "name": "defer",
    "description": "Defer execution until after the document has fully parsed (classic scripts only)"
  },
  {
    "name": "blocking",
    "description": "Mark as render-blocking: set to \"render\" to block page rendering until the script executes"
  },
  {
    "name": "crossorigin",
    "description": "Enable CORS: anonymous (send no credentials) or use-credentials",
    "options": [
      "anonymous",
      "use-credentials"
    ]
  },
  {
    "name": "referrerpolicy",
    "description": "Controls referrer sent when fetching: no-referrer, origin, strict-origin, same-origin, unsafe-url",
    "options": [
      "no-referrer",
      "no-referrer-when-downgrade",
      "origin",
      "origin-when-cross-origin",
      "same-origin",
      "strict-origin",
      "strict-origin-when-cross-origin",
      "unsafe-url"
    ]
  },
  {
    "name": "integrity",
    "description": "Subresource Integrity hash (e.g. sha384-…) to verify the fetched script"
  },
  {
    "name": "fetchpriority",
    "description": "Hint the browser's fetch priority: high, low, or auto (default)",
    "options": [
      "auto",
      "high",
      "low"
    ]
  }
]
